name: premsa-gencat-cron

# Trigger del workflow
on:
  schedule:
    # Executa cada dia a les 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pywikibot paprika

      - name: Run Python script
        run: python premsa_gencat.py
